name: ServicesSoundAlexa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask>=3.1.1
  - numpy>=2.3
  - netifaces>=0.11
  - pyaudio>=0.2.11
  - zeroconf>=0.147
  - pip
  - setuptools
  - wheel
